# GTFS Manager Configuration

# URL to download the GTFS feed from
# feed_url: "https://download.gtfs.de/germany/nv_free/latest.zip"
feed_url: "https://download.gtfs.de/germany/free/latest.zip"

# Local path to store the downloaded GTFS feed
feed_path: "gtfs-data/feeds/20251229_fahrplaene_gesamtdeutschland_gtfs.zip"

# Path to the SQLite database
database_path: "gtfs-data/sqlite/gtfs.sqlite"
