// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDatabaseExists() {
  return window['go']['main']['App']['CheckDatabaseExists']();
}

export function DownloadGTFS(arg1) {
  return window['go']['main']['App']['DownloadGTFS'](arg1);
}

export function ExportJourneyToICS(arg1) {
  return window['go']['main']['App']['ExportJourneyToICS'](arg1);
}

export function ExportJourneyToPDF(arg1) {
  return window['go']['main']['App']['ExportJourneyToPDF'](arg1);
}

export function GetAbsolutePath(arg1) {
  return window['go']['main']['App']['GetAbsolutePath'](arg1);
}

export function GetDatabaseStatus() {
  return window['go']['main']['App']['GetDatabaseStatus']();
}

export function GetNearbyStations(arg1, arg2) {
  return window['go']['main']['App']['GetNearbyStations'](arg1, arg2);
}

export function GetRouteByID(arg1) {
  return window['go']['main']['App']['GetRouteByID'](arg1);
}

export function GetRoutesForStation(arg1) {
  return window['go']['main']['App']['GetRoutesForStation'](arg1);
}

export function GetStationDetails(arg1) {
  return window['go']['main']['App']['GetStationDetails'](arg1);
}

export function GetStops(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetStops'](arg1, arg2, arg3, arg4);
}

export function GetTripDetails(arg1, arg2) {
  return window['go']['main']['App']['GetTripDetails'](arg1, arg2);
}

export function GetUpcomingTripsForStations(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetUpcomingTripsForStations'](arg1, arg2, arg3, arg4);
}

export function GetUserLocation() {
  return window['go']['main']['App']['GetUserLocation']();
}

export function ImportGTFS() {
  return window['go']['main']['App']['ImportGTFS']();
}

export function ImportGTFSFromFile() {
  return window['go']['main']['App']['ImportGTFSFromFile']();
}

export function LoadJourney() {
  return window['go']['main']['App']['LoadJourney']();
}

export function SaveJourney(arg1) {
  return window['go']['main']['App']['SaveJourney'](arg1);
}

export function SearchStations(arg1, arg2) {
  return window['go']['main']['App']['SearchStations'](arg1, arg2);
}

export function ShowConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowConfirmDialog'](arg1, arg2);
}
