// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetStationDetails(arg1:string):Promise<main.StationDetails>;

export function GetStops(arg1:number,arg2:number,arg3:number,arg4:number):Promise<Array<main.Stop>>;

export function Greet(arg1:string):Promise<string>;
