// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRoutesForStation(arg1) {
  return window['go']['main']['App']['GetRoutesForStation'](arg1);
}

export function GetStationDetails(arg1) {
  return window['go']['main']['App']['GetStationDetails'](arg1);
}

export function GetStops(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetStops'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SearchStations(arg1, arg2) {
  return window['go']['main']['App']['SearchStations'](arg1, arg2);
}
