// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';
import {geolocation} from '../models';

export function CheckDatabaseExists():Promise<boolean>;

export function DownloadGTFS(arg1:string):Promise<void>;

export function ExportJourneyToICS(arg1:models.JourneyData):Promise<string>;

export function ExportJourneyToPDF(arg1:models.JourneyData):Promise<string>;

export function GetAbsolutePath(arg1:string):Promise<string>;

export function GetDatabaseStatus():Promise<main.DatabaseStatus>;

export function GetNearbyStations(arg1:string,arg2:number):Promise<Array<models.Stop>>;

export function GetRouteByID(arg1:string):Promise<models.Route>;

export function GetRoutesForStation(arg1:string):Promise<models.RoutesData>;

export function GetStationDetails(arg1:string):Promise<models.StationDetails>;

export function GetStops(arg1:number,arg2:number,arg3:number,arg4:number):Promise<Array<models.Stop>>;

export function GetTripDetails(arg1:string,arg2:string):Promise<models.TripDetails>;

export function GetUpcomingTripsForStations(arg1:Array<string>,arg2:string,arg3:number,arg4:Array<number>):Promise<models.UpcomingTripsData>;

export function GetUserLocation():Promise<geolocation.LocationResult>;

export function ImportGTFS():Promise<void>;

export function ImportGTFSFromFile():Promise<void>;

export function LoadJourney():Promise<main.LoadJourneyResult>;

export function SaveJourney(arg1:models.JourneyData):Promise<string>;

export function SearchStations(arg1:string,arg2:number):Promise<Array<models.Stop>>;

export function ShowConfirmDialog(arg1:string,arg2:string):Promise<boolean>;
